name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - S_portfolio-PP   # change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20    # ✅ upgraded from 18 → 20
          cache: 'npm'        # ✅ cache npm packages for speed + fewer errors

      - name: Install dependencies
        run: npm ci           # ✅ cleaner + faster than npm install in CI/CD

      - name: Build React App
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: senkusha.in   # ✅ custom domain will still work
